DISCORD_HOME_CHANNEL: '1483199527581253692'
agent:
  max_turns: 3
  reasoning_effort: medium
discord:
  auto_thread: false
  free_response_channels: '1483199527581253692'
  require_mention: false
memory:
  memory_enabled: true
model: anthropic/claude-sonnet-4-20250514
platform_toolsets:
  discord:
    - gossip
    - memory
    - skills
    - search
    - clarify
    - cronjob
session_reset:
  idle_minutes: 1440
  mode: idle
